### ISSUE TITLE
[README.md] Dead links with the inexistent `scaffolding` folder

### ISSUE THREAD

**Issue by alexisbertin** [turbulent/bemex#2]
### Screenshot:

> <img width="343" alt="capture d ecran 2018-10-10 a 03 50 49" src="https://user-images.githubusercontent.com/26164711/46720925-cbdc0480-cc3f-11e8-93aa-23b971d1fc5d.png">

### Location:

**l.9** of `README.md`: 
```
Download project scaffolding: [LESS](./scaffolding/less) | [SASS](./scaffolding/sass)
```

### Description:
Both links aren't working, probably due to a lack of permissions.
How public is this repo supposed to be? So far only the specs and examples are publicly accessible.

**Comment by psaunders** [comment]
We actually decided to take the scaffolding and merge it into different examples. So this could be removed.
